updating precommit

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -2,22 +2,33 @@
 
 stagedFiles=$(git diff --staged --name-only)
 
+# Run spotlessApply
 echo "Running spotlessApply"
 ./gradlew spotlessApply
+RESULT=$?  # Capture the exit status of spotlessApply
 
+# Check if RESULT is not 0, which indicates an error
+if [ $RESULT -ne 0 ]; then
+    echo "spotlessApply failed."
+    exit 1
+fi
+
+# Add modified files back to staging
 for file in $stagedFiles; do
     if test -f "$file"; then
-        git add $file
-        echo $file
+        git add "$file"
+        echo "Added to staging: $file"
     fi
 done
 
-[ $RESULT -ne 0 ] && exit 1
-
+# Run Unit Tests
 echo "Running Unit Tests"
 ./gradlew test
 status=$?
 if [ $status -ne 0 ]; then
+    echo "Unit Tests failed."
     exit 1
 fi
+
+echo "Pre-commit checks passed."
 exit 0
